# Generated by Django 3.0.3 on 2020-07-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200707_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default='media/placeholder.jpg', null=True, upload_to=''),
        ),
    ]
